adding simulating error in yaml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,3 +10,6 @@ jobs:
     - uses: actions/checkout@v3
     - name: Run a simple github action
       run: echo "this workflow run successfully for this action"
+
+    - name: $Simulating Error
+      run: echo "error taking place" exit 1 
